In [1]:
# EX 1

import numpy as np
import time
import matplotlib.pyplot as plt

In [54]:
# 1.a

def contraction(G, e):
        
    # récupération des indice des deux sommets à fusionner
    x,y = e
    
    # on va "désactiver" le sommet y pour garder en x la fusion des deux
    
    # récupération du nombre d'arête entre y et chaque autre sommet
    fus_l = G[y,:]


    # on met à jour le sommet x
    G[x,:] += fus_l
    G[:,x] += fus_l
    
    G[x,x] = 0
    
    # on "desactive" le sommet y
    G[y,:] = np.zeros(len(G))
    G[:,y] = np.zeros(len(G))
    
    return G, y


In [92]:
# 1.b

G1 = np.array([[1,2,0,1],
     [2,0,3,1],
     [0,3,1,1],
     [1,1,1,0]])

e = [0,1]

#plt.plot(100, log_tps , "r",)
#plt.show()

0.0002669523000717163
0.00025917439460754394


In [4]:
# graph complet
tps_complet = []
e = [0,1]

for i in range(10000):
    G = np.ones((500,500))
    
    debut = time.time()
    G_c, y = contraction(G,e)
    
    fin = time.time()
    tps_complet.append(fin-debut)
    
tps_complet_2 = []

for i in range(10000):
    G = np.ones((500,500))*2
    
    debut = time.time()
    G_c, tps = contraction(G,e)
    
    fin = time.time()
    tps_complet_2.append(fin-debut)

print(np.mean(tps_complet))
print(np.mean(tps_complet_2))

1.190180778503418e-05
1.002213954925537e-05


In [5]:
tps_cycle = []

for i in range(10000):
    G = np.zeros((500,500))
    np.fill_diagonal(G[:,1:], 1)
    G[-1,0] = 1
    
    debut = time.time()
    G_c, tps = contraction(G,e)
    
    fin = time.time()
    tps_cycle.append(fin-debut)
    
print(np.mean(tps_cycle))


1.0719966888427735e-05


In [6]:
tps_proba = []

for i in range(10000):
    G = np.random.randint(2, size = (500,500))
    
    debut = time.time()
    G_c, tps = contraction(G,e)
    
    fin = time.time()
    tps_proba.append(fin-debut)
    
print(np.mean(tps_proba))


1.166231632232666e-05


In [66]:
# 1.c

def selectRandom(V,G):
    
    x = np.random.choice(V)
    y = np.random.choice(V)
    
    while (G[x,y]==0):
        x = np.random.choice(V)
        y = np.random.choice(V)
                
    return x,y

In [74]:
def karger(G):
    V = [*range(len(G))]
    S = []
    
    while len(V) > 2:
        e = selectRandom(V, G)
        
        G ,y = contraction(G,e)
        
        V.remove(y)
        S.append(y)
        
    return S
    

In [75]:
G1 = np.array([[0,1,0,0,0,0],
               [1,0,1,0,1,0],
               [0,1,0,1,1,0],
               [0,0,1,0,0,1],
               [0,1,1,0,0,1],
               [0,0,0,1,1,0]])

print(G1)
print(karger(G1))

[[0 1 0 0 0 0]
 [1 0 1 0 1 0]
 [0 1 0 1 1 0]
 [0 0 1 0 0 1]
 [0 1 1 0 0 1]
 [0 0 0 1 1 0]]
[0, 4, 3, 1]


In [81]:
# 1.e
# Dictionnaire {"Key :[sommet]" : "successeur :[(sommet, nb d'arêtes)]"}

#n1 = {[1], "succ": [{n2, 1}]}
g = {'1' : [(2, 1)],
    '2' : [(1,1), (3,1), (5,1)],
    '3' : [(2,1), (4,1), (5,1)],
    '4' : [(3,1), (6,1)],
    '5' : [(2,1), (3,1), (6,1)],
    '6' : [(4,1), (5,1)]}

print(g['1'])



[{1, 2}]


In [ ]:
def contraction_2(G, e):
        
    # récupération des indice des deux sommets à fusionner
    x,y = e
        
    # récupération du nombre d'arête entre y et chaque autre sommet
    Gx = G[str(x)]
    Gy = G[str(y)]

    G_new = Gx
    for elm in Gy:
        if elm not in G_new:
            G_new.append(elm)
        else:
            G_new[elm][1] +=1
            
    G_new.remove()

    
    return G, y